# fly.toml app configuration file generated for qb on 2023-09-16T21:20:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "qb"
primary_region = "iad"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "sh release.sh"

[env]
  PORT = "8000"
  USE_S3 = true

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
