# Generated by Django 5.0a1 on 2023-09-22 18:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_question_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
