# Generated by Django 5.0a1 on 2023-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_phone"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "question"), name="unique_question_bookmark"
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=("user", "answer"), name="unique_answer_bookmark"
            ),
        ),
    ]
